theman550/DAT257-K9

README.md
La in lite arbetsregler i readme samt en länk till scrum board
=> Update readme with rules

.github/workflows/frontend.yml, frontend/package-lock.json, frontend/package.json, frontend/public/index.html, frontend/src/App.js, frontend/src/App.test.js, frontend/src/components/Navigation.js, frontend/src/components/Navigation.test.js
Har fixat en basic navbar på toppen som använder sig av React Router: https://reactrouter.com/web/guides/quick-start
Har även experimenterat lite med Styled Components som gör det extremt lätt och modulärt att styla komponenterna: https://styled-components.com/docs/basics
Jag vill gärna veta vad ni tror om att använda styled components? Biblioteket är extremt lätt, det skapar nya komponenter med lite styling utifrån befintliga komponenter, och de görs inuti komponenterna så att det blir lätt att ändra och stör inte andra komponenter.
=> Navigera resehantering

backend/html/api.php
La till användarID och reseID som filter i readTrips samt fixade några gamla funktioner så att de funkar med nya de nya identifierarna i databasen.
Flyttade writeTrip()-testet från main-loopen så att vi inte får en ny resa vid varje API-call.
=> Nya parametrar för readTrips

backend/html/api.php, backend/html/connectDB.php
Query error check, test funktion, funktion som filtrerar gamla resor. Testfunktion ska flyttas till en annan fil senare med alla test funktioner.
=> Querry error + funktioner och test

frontend/package.json, frontend/src/App.js, frontend/src/components/Notification.js, frontend/src/components/Notification.test.js
Har skapat ett simpelt notifikationssystem som fungerar genom att man skickar funktionen `showNotification` till sin komponent och använder den genom att skriva `showNotification(meddelande, färg för notifikationen (t.ex 'green'), hur många sekunder den ska visas)`. Notifikationen visas då under navbaren och försvinner efter angiven tid.
=> Notification system

frontend/src/App.js
styled-components använder ThemeProvider för att definiera globala variabler såsom färgschema, spacing, m.m.
Har för tillfället enbart lagt till färgschemat. Se App.jsx för exempel.
Rekommenderar att alla uppdaterar sina färg hexkoder till att referera till färgschemat.
=> Implement theme provider with a global color scheme

frontend/src/screens/Trip/Display.jsx, frontend/src/screens/Trips.js
Uppdaterade även min API endpoint till det nya REST interface.
=> Add display screen to trips route

frontend/public/index.html
En liten ändring till body. Tog bort default margin/padding, vet inte varför det är där från början. La till en default bakgrundsfärg enligt färgschemat.
=> Change default HTML styling to our design's

frontend/package-lock.json, frontend/src/App.js, frontend/src/components/Trip/Card/Card.jsx, frontend/src/components/Trip/Card/Card.test.jsx, frontend/src/components/UI/Card/Card.jsx, frontend/src/components/UI/Card/Card.test.jsx, frontend/src/components/UI/Field.jsx, frontend/src/components/trips/FloatingButtons.test.js, frontend/src/components/trips/SearchTrips.test.js, frontend/src/themes/base.js
Flyttade theme objektet från App.js till sin egna mapp, 'src/themes'. Importerade theme basen i olika test filer så samma theme inte står deklarerade på många olika ställen(svårt att hålla reda på).
Uppdaterade mina komponenter till att använda spacing samt padding från theme konfigurationen. Rekommenderar att ni läser 'src/themes/base.js' och dess kommentarer för att förstå hur dessa ska användas. Om ni vill ha exempel så har ni kort komponenterna att utgå ifrån(dessa är dock inte perfekt stylade).
=> Move theme to its own module, add spacing and padding

README.md
La till lite rekommendationer samt exempel på hur man i koden når färgschemat och andra variabler från det valda temat.
Något som fattas?
=> Update README with styling documentation and recommendations

README.md
La till lite om konfigurationens syfte samt hur man använder den i koden.
Skrev även till en punkt i "Styling frontend" sektionen om att alla komponenter ska vara responsivt stylade.
=> Write about the configuration's purpose and how to use it in README

backend/html/api.php, backend/html/api/trips/index.php, backend/html/api/users/index.php
REST API för api/users/  , GET -> Användarinformation utifrån satta filter(userID, email, firstnamne, lastname), 
POST -> lägger till nytt konto(mailen får inte redan finnas i databasen, enda villkoret)
=> Thezzern patch 1

frontend/public/index.html, frontend/src/App.js, frontend/src/App.test.js, frontend/src/components/Navigation.js, frontend/src/components/Navigation.test.js, frontend/src/components/trips/FloatingButtons.js, frontend/src/screens/Account.js, frontend/src/screens/Trip/Display.jsx
Saker i denna PR:
- Fixade till CSS reset i index.html så att padding inte bygger på total width för en komponent, med hjälp av box-sizing.
- Gjorde också så att alla komponenter tar del av CSS reset med hjälp av *.
- Har gjort om hela navbaren så den mer liknar mockups samt ändrat adresserna.
- Navbaren är även responsiv och visar loggan till vänster på skärmar större än 765px.
- Lade till lite margin top och bottom i Display så att den inte börjar under navbaren, och inte slutar under de runda knapparna.
- Ändrade också fetch-adressen i Display eftersom den var fel.
=> New navbar

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/App.test.js, frontend/src/components/ErrorBoundary.jsx, frontend/src/components/ErrorBoundary.test.jsx, frontend/src/enzyme.js
Lade till en ErrorBoundary komponent som kan läggas runt en eller flera komponenter. Den fångar eventuella errors som inte hanteras av dess child komponenter och därefter stoppar den komponenterna från att rendras och visar ett felmeddelande. Denna error boundary kan användas runt vilka komponenter som helst. Har börjat med att lägga den runt varje routeable sida.
Men idéen är att man kan använda den runt sina komponenter om sina komponenter utgör en avskild funktion. Ett exempel är Facebooks chattfönster på webben. Vid chattrelaterade fel stänger Facebook ner klientens chattfönster gentemot hela sidan. I detta exempel använder Facebook en error boundary runt hela sidan och en inre error boundary runt chattfönstret. Om ett error fångas tidigt av en inre error boundary så slutar error …
=> Implement error boundary with purpose to catch errors in certain groups of components

frontend/src/components/UI/ButtonBase.jsx, frontend/src/components/UI/InactiveButton.jsx, frontend/src/components/UI/PrimaryButton.jsx, frontend/src/components/UI/index.jsx, frontend/src/components/trips/AddTrip.js, frontend/src/components/trips/SearchTrips.js
- La till en "InactiveButton" som en återanvändbar komponent likt PrimaryButton.
- Uppdaterade SearchTrips och AddTrips till att använda den nya knappen.
=> Add inactive button as reusable component

backend/html/api.php, backend/html/api/book/index.php, backend/html/booking.php, backend/html/connectDB.php, backend/html/dataValidation.php, backend/html/test.html
Grundläggande funktionalitet för bookings. Tog även bort integer-kontrollen från price och seats samt gjorde så att connectDB returnerar fel.
=> La till booking & småfixar

frontend/src/components/trips/Pagination.js, frontend/src/components/trips/Pagination.test.js, frontend/src/components/trips/SearchTrips.js, frontend/src/components/trips/SearchTrips.test.js, frontend/src/screens/Trip/Display.jsx, frontend/src/screens/Trips.js
Denna PR adderar pagination till trips. För att få detta att fungera så valde jag att refaktorera hämtningen av trips från Display och SearchTrips till Trips eftersom det är lättare att hantera nuvarande trips på ett ställe.
Edit: Det verkar som att det är problem med backend för tillfället så den fetchar inte trips. Detta gör det svårt att se pagination eftersom den inte visas när antal trips är 0.
=> Trips pagination

frontend/src/App.js, frontend/src/components/Form.js, frontend/src/components/LoginForm.js, frontend/src/screens/Login.js
moving to tips page when signed in
=> when user signed in move to trips

frontend/src/components/trips/AddTrip.js, frontend/src/model/Trip.js, frontend/src/screens/Trips.js
Är ett problem med min senaste commit, vet inte om det är värt att merga ändå.
Den enda skillnaden är att man inte kan boka den nya resan som man själv lagt till.
Eftersom vi inte har userID i user payload kan jag inte lägga till det i den nya resan.
Vilket gör att BookCard blir arg eftersom den kräver userID för att boka resa.
Tänkte främst lägga in detta då det är mer demonstrativt under presentationen, att själva listan uppdateras direkt utan refresh. Refresh i säg skapar problem för då måste man logga in igen.
=> Format add trip's date and update list of trips after successful add trip

frontend/src/components/Trip/Card/CancelCard.jsx, frontend/src/screens/Account.jsx
Pröva att boka en trip, och sedan avboka den i account skärmen!
=> Remove trip from user's bookings if its booking was canceled
